/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nomina;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.plaf.OptionPaneUI;

/**
 *
 * @author cris_
 */
public class Calculo extends javax.swing.JFrame {

    /**
     * Creates new form Calculo
     */
    public Calculo() {
        initComponents();
        txtSalario.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtPrima = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        txtVacaciones = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDiasVaca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JFormattedTextField();
        txtAnios = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mi nomina");
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        lblTitulo.setText("CALCULO DE NOMINA");

        txtPrima.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPrima.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPrima.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Salario Diario $");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Años de servicio");

        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        btnCalcular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCalcularKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnCalcularKeyReleased(evt);
            }
        });

        txtVacaciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtVacaciones.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtVacaciones.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Prima Vacacional 25%");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Dias de vacaciones y pago");

        txtDiasVaca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDiasVaca.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDiasVaca.setEnabled(false);

        jLabel1.setText("Version 1.0");

        txtSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###.00"))));
        txtSalario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSalarioKeyPressed(evt);
            }
        });

        txtAnios.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##"))));
        txtAnios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAnios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAniosKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnios, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPrima, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtDiasVaca, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtVacaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(33, 33, 33)))))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(149, 149, 149))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitulo)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtAnios, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVacaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiasVaca, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void calcular(String opcion, double salario){
        double vacaciones;
        switch (opcion){
            case "1":
                vacaciones = 6*salario;
                txtVacaciones.setText(String.valueOf(vacaciones));
                txtDiasVaca.setText("6");
                break;
            case "2":
                vacaciones = 8*salario;
                txtVacaciones.setText(String.valueOf(vacaciones));
                txtDiasVaca.setText("8");
                break;
            case "3":
                vacaciones = 10*salario;
                txtVacaciones.setText(String.valueOf(vacaciones));
                txtDiasVaca.setText("10");
                break;
            case "4":
                vacaciones = 12*salario;
                txtVacaciones.setText(String.valueOf(vacaciones));
                txtDiasVaca.setText("12");
                break;
            case "5-9":
                vacaciones = 14*salario;
                txtVacaciones.setText(String.valueOf(vacaciones));
                txtDiasVaca.setText("14");
                break;
            case "10-14":
                vacaciones = 16*salario;
                txtVacaciones.setText(String.valueOf(vacaciones));
                txtDiasVaca.setText("16");
                break;
            case "15-19":
                vacaciones = 18*salario;
                txtVacaciones.setText(String.valueOf(vacaciones));
                txtDiasVaca.setText("18");
                break;
            case "20-24":
                vacaciones = 20*salario;
                txtVacaciones.setText(String.valueOf(vacaciones));
                txtDiasVaca.setText("20");
                break;
            case "25-29":
                vacaciones = 22*salario;
                txtVacaciones.setText(String.valueOf(vacaciones));
                break;
            case "30-34":
                vacaciones = 24*salario;
                txtVacaciones.setText(String.valueOf(vacaciones));
                txtDiasVaca.setText("24");
                break;
            case "35-39":
                vacaciones = 26*salario;
                txtVacaciones.setText(String.valueOf(vacaciones));
                txtDiasVaca.setText("26");
                break;
                
        }
    }
    
    public void obtenerDatos(){
        String opcion = null;
        double salario = Double.parseDouble(txtSalario.getText());
        double prima = salario*.25;
        txtPrima.setText(String.valueOf(prima));
             
        int aniosInt = Integer.parseInt(txtAnios.getText());
        
        if (aniosInt < 36){
            if ( "1".equals(txtAnios.getText())){
                opcion = "1";
            }
            if ( "2".equals(txtAnios.getText())){
                opcion = "2";
            }
            if ( "3".equals(txtAnios.getText())){
                opcion = "3";
            }
            if ( "4".equals(txtAnios.getText())){
                opcion = "4";
            }
            if (aniosInt>=5 && aniosInt<=9){
                opcion = "5-9";
            }
            if (aniosInt>=10 && aniosInt<=14){
                opcion = "10-14";
            }
            if (aniosInt>=15 && aniosInt<=19){
                opcion = "15-19";
            }
            if (aniosInt>=20 && aniosInt<=24){
                opcion = "20-24";
            }
            if (aniosInt>=25 && aniosInt<=29){
                opcion = "25-29";
            }
            if (aniosInt>=30 && aniosInt<=34){
                opcion = "30-34";
            }
            if (aniosInt>=35 && aniosInt<=39){
                opcion = "35-39";
            }
            calcular(opcion, salario);
        }else{
            JOptionPane.showMessageDialog(null, "Los años no deben exeder de 39");
            txtAnios.setText(null);
            
        }
        
        
    }
    
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
       
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnCalcularKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCalcularKeyReleased
        
    }//GEN-LAST:event_btnCalcularKeyReleased

    private void btnCalcularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCalcularKeyPressed
    char car=(char) evt.getKeyCode();
        if(car==evt.VK_ENTER){
           obtenerDatos();
           txtSalario.requestFocus();
        }   
    }//GEN-LAST:event_btnCalcularKeyPressed

    private void txtSalarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalarioKeyPressed
        char car=(char) evt.getKeyCode();
        if(car==evt.VK_ENTER){
           txtAnios.requestFocus();
        }   
    }//GEN-LAST:event_txtSalarioKeyPressed

    private void txtAniosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAniosKeyPressed
        char car=(char) evt.getKeyCode();
        if(car==evt.VK_ENTER){
           btnCalcular.requestFocus();
        }  
    }//GEN-LAST:event_txtAniosKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JFormattedTextField txtAnios;
    private javax.swing.JTextField txtDiasVaca;
    private javax.swing.JTextField txtPrima;
    private javax.swing.JFormattedTextField txtSalario;
    private javax.swing.JTextField txtVacaciones;
    // End of variables declaration//GEN-END:variables
}
